replicaCount: 3
revisionHistoryLimit: 5

strategy:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

image:
  repository: myrepo/myservice
  tag: latest
  pullPolicy: IfNotPresent

container:
  port: 8081

prometheus:
  scrape: "true"
  port: "8081"

serviceAccount:
  name: myservice-sa

env:
  javaOpts: "-Xms512m -Xmx1024m"
  springProfile:
    configMapName: myservice-config
    key: activeProfile

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

dnsPolicy: Default
restartPolicy: Always

imagePullSecrets: my-docker-secret
