replicaCount: 3
revisionHistoryLimit: 5

strategy:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

image:
  repository: myrepo/myservice
  tag: latest
  pullPolicy: IfNotPresent

container:
  port: 8081

service:
  name: my-app
  fullname: dev-my-app
  type: LoadBalancer
  port: 80
  targetPort: 8081
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/metrics"

env:
  javaOpts: "-Xms512m -Xmx1024m"
  springProfile:
    configMapName: myapp-config
    key: activeProfile

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

dnsPolicy: Default

imagePullSecrets: my-docker-secret
